# netlify.toml (Versi untuk Jekyll)

[build]
  # Folder output default Jekyll adalah _site
  publish = "_site" 
  command = """
    # --- Konfigurasi Awal ---
    GREEN='\\033[0;32m'
    YELLOW='\\033[1;33m'
    RED='\\033[0;31m'
    CYAN='\\033[0;36m'
    NC='\\033[0m' # No Color

    # !! PENTING: Ganti dengan domain Anda !!
    HOST="your-jekyll-site.com" 
    # Path sitemap di dalam folder output Jekyll
    SITEMAP_PATH="_site/sitemap.xml"
    
    # --- Proses Build Jekyll ---
    echo -e "${CYAN}🚀 Memulai proses build Jekyll...${NC}"
    # Gunakan 'bundle exec' untuk memastikan versi yang benar
    if ! bundle exec jekyll build; then
      echo -e "${RED}❌ Build Jekyll gagal. Proses IndexNow dibatalkan.${NC}"
      exit 1
    fi
    echo -e "${GREEN}✅ Build Jekyll berhasil.${NC}"

    # --- Validasi Sitemap ---
    if [ ! -f "$SITEMAP_PATH" ]; then
      echo -e "${RED}❌ File sitemap.xml tidak ditemukan di '$SITEMAP_PATH'. Proses IndexNow dilewati.${NC}"
      exit 0
    fi

    # --- Parsing URL dari Sitemap ---
    echo -e "${CYAN}📄 Mem-parsing sitemap.xml untuk URL terbaru...${NC}"
    TODAY=$(date -u +"%Y-%m-%d")

    # Mengambil semua URL yang dimodifikasi hari ini.
    # Filter ini (tags/categories) mungkin perlu disesuaikan dengan struktur URL Jekyll Anda.
    URLS_TODAY=$(grep -E '<loc>|<lastmod>' "$SITEMAP_PATH" \\
      | sed -e 's/<loc>//;s|</loc>||;s/<lastmod>//;s|</lastmod>||' \\
      | paste -d' ' - - \\
      | grep "$TODAY" \\
      | grep -vE '/tags/|/categories/' \\
      | awk '{print $1}')

    if [ -z "$URLS_TODAY" ]; then
      echo -e "${YELLOW}ℹ️ Tidak ada URL baru atau yang diperbarui hari ini. Pengiriman ke IndexNow dilewati.${NC}"
      exit 0
    fi

    URL_COUNT=$(echo "$URLS_TODAY" | wc -l | xargs)
    echo -e "${GREEN}📅 Ditemukan ${URL_COUNT} URL untuk dikirim ke IndexNow.${NC}"
    echo "$URLS_TODAY"

    # --- Persiapan dan Pengiriman ke IndexNow ---
    URL_JSON_ARRAY=$(printf '"%s",' $URLS_TODAY | sed 's/,$//')

    JSON_PAYLOAD=$(cat <<EOF
{
  "host": "${HOST}",
  "key": "${INDEXNOW_KEY}",
  "keyLocation": "https://${HOST}/${INDEXNOW_KEY_FILENAME}",
  "urlList": [${URL_JSON_ARRAY}]
}
EOF
)

    echo -e "${CYAN}📦 Payload JSON yang akan dikirim:${NC}"
    echo "$JSON_PAYLOAD"

    echo -e "${CYAN}📤 Mengirim daftar URL ke API IndexNow...${NC}"
    RESPONSE_CODE=$(curl --silent --output /dev/null --write-out "%{http_code}" \\
      --request POST "https://api.indexnow.org/indexnow" \\
      --header "Content-Type: application/json" \\
      --data "${JSON_PAYLOAD}")

    # --- Analisis Respons ---
    echo -e "${CYAN}📡 Menerima respons dari IndexNow...${NC}"
    if [ "$RESPONSE_CODE" -ge 200 ] && [ "$RESPONSE_CODE" -lt 300 ]; then
      echo -e "${GREEN}✅ Berhasil! IndexNow merespons dengan status HTTP: ${RESPONSE_CODE}${NC}"
    else
      echo -e "${RED}❌ Gagal! IndexNow merespons dengan status HTTP: ${RESPONSE_CODE}${NC}"
      echo -e "${RED}   Pastikan variabel INDEXNOW_KEY dan INDEXNOW_KEY_FILENAME sudah benar di pengaturan Netlify.${NC}"
    fi
  """

# Anda mungkin perlu menentukan versi Ruby jika Netlify tidak mendeteksinya secara otomatis
# [build.environment]
#   RUBY_VERSION = "3.0.2"
